project:
  type: website
  output-dir: _site

website:
  title: "R Bootcamp"
  favicon: assets/princeton-favicon.svg
  page-navigation: true
  navbar:
    title: "R Bootcamp"
    left:
      - href: day-1.qmd
        text: Day 1
      - href: day-2.qmd
        text: Day 2
      - href: day-3.qmd
        text: Day 3
      - href: day-4.qmd
        text: Day 4
    right:
      - href: prerequisites.qmd
        text: Prerequisites
      - href: data.qmd
        text: Data
      - href: about.qmd
        text: About
  page-footer:
    left: '<img class="footer-logo" src="assets/DDSS-stacked_PU_shield_black.webp" alt="Data-Driven Social Science at Princeton University">'
    right: "R Bootcamp"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
